add 2-module 1/2/3-task
js-tasks-ru/jsbasic-20220418-2_so1que pull request #3
Opened 2022-04-21 20:45 UTC by So1que

2022-04-21 20:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-22 14:06 UTC, SinimaWath requested changes

2022-04-22 14:06 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    calculator.a = +a;
В этом примере надо использовать this.

2022-04-24 15:41 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-24 19:35 UTC, SinimaWath approved these changes

2022-04-24 19:35 UTC, merged